name: QUXUQ2

on:
  schedule:
    - cron: '*/16 * * * *'  # 16分ごとに実行
  workflow_dispatch:         # 手動実行も可能

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 依存関係のインストール
        run: |
          pip install tweepy

      - name: QUXUQ2 実行
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python QUXUQ2.py

      - name: replied_users.json をアーティファクトとして保存
        if: success()  # スクリプトが成功したときだけ保存
        uses: actions/upload-artifact@v4
        with:
          name: replied-users-log
          path: replied_users.json
